# XArm6 硬件配置
robot:
  addr: "192.168.31.232"
  dof: 6
  gripper_range: [0, 840]  # 闭合~张开

cameras:
  arm:
    serial: "327122075644"   # D435i
    mode: "rgbd"
  fix:
    serial: "f1271506"       # L515
    mode: "rgbd"

# 采集默认参数
collect:
  image_size: [320, 240]     # W, H
  warmup_time: 1.0
  control_speed: 100         # Cartesian speed during collect
